### ISSUE TITLE
DatabaseConnector_mysql uses deprecated PHP MySQL extension.

### ISSUE THREAD

**Issue by austindunn** [IMSGlobal/LTI-Tool-Provider-Library-PHP#1]
The DatabaseConnector_mysql class, located inside src/ToolProvider/DataConnector, uses the mysql extension, no longer allowed by PHP. This should be updated to use the improved mysqli extension. More info here: http://php.net/manual/en/book.mysqli.php

**Comment by spvickers** [comment]
This is just one of the options available for this library - another already provided is for PDO connections.  More will be added later.
