### ISSUE TITLE
LTI Advantage support (and is this project still active?)

### ISSUE THREAD

**Issue by kenianbei** [IMSGlobal/LTI-Tool-Provider-Library-PHP#43]
Hi, I'm just wondering if IMS Global is still supporting this project and if it will be updating it when LTI Advantage specs are released?

**Comment by jrissler** [comment]
Hi - @kenianbei we will not be official supporting the maintenance of this project for LTI Advantage. However we do have a member that has written PHP code around LTI Advantage and will be linking that to readme once we get a final update or two in here soon.
