### ISSUE TITLE
Can't use method return value

### ISSUE THREAD

**Issue by harishannam** [IMSGlobal/LTI-Tool-Provider-Library-PHP#6]
Fatal error: Can't use method return value in write context in /opt/xdrive2/itsmecheck/ec2_files/new_imc/files/imc_lti/vendor/imsglobal/lti/src/ToolProvider/DataConnector/DataConnector_pdo.php on line 53

I am using PHP 5.3 and I get this error.

**Comment by spvickers** [comment]
Thanks for bringing this to our attention.  It looks like a limitation of PHP < 5.5 so, given that these releases of PHP are now old and not supported, I would recommend that you update your version of PHP.  I will update the documentation to note that PHP 5.6+ is required, as this is the oldest version which is still supported.
