### ISSUE TITLE
launch_presentation_return_url is recommended in spec, but required in the library

### ISSUE THREAD

**Issue by xow** [IMSGlobal/LTI-Tool-Provider-Library-PHP#7]
Had a bug report from someone pointing out that if launch_presentation_return_url is not included the registration request fails, despite the fact that it's only recommended and not required in the spec.

**Comment by spvickers** [comment]
The LTI 2.0 specification states that this is a required parameter for a Tool Proxy Registration reqiest message so this seems to be correct behaviour; see:
  https://www.imsglobal.org/specs/ltiv2p0/implementation-guide#toc-43
